@startuml
set separator none
title e - Dynamic

!pragma teoz true
skinparam {
  arrowFontSize 10
  defaultTextAlignment center
  wrapWidth 200
  maxMessageSize 100
}

hide stereotype

skinparam sequenceParticipant<<A.B.C>> {
  BackgroundColor #dddddd
  FontColor #000000
  BorderColor #9a9a9a
  shadowing false
}
skinparam sequenceParticipant<<d.e.f>> {
  BackgroundColor #dddddd
  FontColor #000000
  BorderColor #9a9a9a
  shadowing false
}
skinparam sequenceParticipant<<d.e.g>> {
  BackgroundColor #dddddd
  FontColor #000000
  BorderColor #9a9a9a
  shadowing false
}
skinparam sequenceParticipant<<d.e.h>> {
  BackgroundColor #dddddd
  FontColor #000000
  BorderColor #9a9a9a
  shadowing false
}
skinparam rectangle<<A.B>> {
  BorderColor #9a9a9a
  FontColor #9a9a9a
  shadowing false
}

skinparam rectangle<<d.e>> {
  BorderColor #9a9a9a
  FontColor #9a9a9a
  shadowing false
}

skinparam box {

}
<style>
    box {
       .A {
       BackgroundColor #9a9a9a
       FontColor Red
       }
    }
</style>

box "A" <<A>>
   box "B" <<A.B>>
      participant "C<size:10>[ComponentPP]</size>" as A.B.C <<A.B.C>> #dddddd
   end box
end box
 @enduml